name: Continuos integration - CI

on: push

jobs:
  build-lint-test:
    name: Install packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use Nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing packages
        run: npm ci

      - name: Check linter
        run: npm run check-lint

      - name: Upload lint result
        uses: actions/upload-artifact@v2
        with:
          name: linter
          path: result-lint.txt

      - name: Runing test
        run: npm test

      - name: Upload tests result
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test-result.txt