name: Deploy to digital ocean

on: push

jobs:
  build_image:
    name: Dockerized app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get release version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF//\//-})

      - name: Building image based on Docker file
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vickvasquez/test-github-actions/test-github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }}"
